project/students/models.py
from project import db,app

class Students(db.Model):

    __tablename__ = 'students'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True)
    age = db.Column(db.Integer)
    img = db.Column(db.String(50))
    

    # initialise an instance (row) of a table/entity
    def __init__(self, name, age,img):
        self.name = name
        self.img = img
        self.age = age


    # __repr__ is used to represent an instance, such as for print() function
    def __repr__(self):
        return f"Name: {self.name}"
with app.app_context():
    db.create_all()

project/students/forms.py
#form imports
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField,IntegerField
from wtforms.validators import DataRequired

# Flask forms (wtforms) allow you to easily create forms in format:
# variable_name = Field_type('Label that will show', validators=[V_func1(), V_func2(),...])
class AddStudent(FlaskForm):
    name = StringField('student name', validators=[DataRequired()])
    age = IntegerField('student age')
    submit = SubmitField('add a student')

project/students/__init__.py
# this file allows us to import components into main app.py file
# python needs this for it to understand that this is a module that it can import

project/students/views.py
import json
from unicodedata import name
from flask import render_template, url_for, redirect, Blueprint
from project import db,app
from project.students.models import Students
from project.students.forms import AddStudent

# image upload
from distutils.log import debug
import os
from flask import  flash, request
from werkzeug.utils import secure_filename
from flask import send_from_directory


students = Blueprint('students', __name__, template_folder='templates',url_prefix='/students')

# UPLOAD_FOLDER = 'UPLOAD_FOLDER'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

# display images from server
@students.route('/uploads/<name>')
def download_file(name):
    return send_from_directory("../" +os.path.join(app.config['UPLOAD_FOLDER']), name)

# check what type allow
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@students.route('/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        # print( request.form.get("author"))
        

        
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            student = Students(name=request.form.get("stdent_name"),age=request.form.get("age"),img=filename)
            db.session.add(student)
            db.session.commit()
            print(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            # return redirect(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            return redirect(url_for('students.list_students'))
    return  render_template('upl.html')



# add a new student

@students.route('/test', methods=['GET'])
def test():
    return "test"


@students.route('/add_student', methods=['GET', 'POST'])
def add_student():
    form = AddStudent()

    if form.validate_on_submit():

        student = Students(name=form.name.data,age=form.age.data)

        db.session.add(student)
        db.session.commit()

        return redirect(url_for('students.list_students'))
    return render_template('add_student.html', form=form)


@students.route('/students_lst')
def list_students():
    stu_list = Students.query.all()
    # JSON instead HTML
    # res = []
    # for x in clubs_list:
    #     res.append({x.name: x.description})
    # return json.dumps(res)
    return render_template('students.html', stu_list=stu_list)

project/students/templates/add_student.html
{% extends 'base.html' %}

{% block content %}

  {% macro validate_field(field) %}
    {% if field.errors %}
      <div class=errors>
      {% for error in field.errors %}
        <p>{{ error }}</p>
      {% endfor %}
    </div>
    {% endif %}
  {% endmacro %}

  <h1> Create a new Student</h1>

  <form method="POST" action="#">
      {{ form.csrf_token }}
          {{ form.name.label }}
          {{ form.name }}
          {{ validate_field(form.name) }}<br><br>

          {{ form.age.label }}
          {{ form.age }}
          {{ validate_field(form.age) }}<br><br>

          {{ form.submit() }}

  </form>
{% endblock %}

project/students/templates/students.html
{% extends 'base.html' %}

{% block content %}
  <h1>List students</h1><br>

    {% for student in stu_list %}
    name:<h2> {{ student.name }} </h2>
        age:<p> {{ student.age }} </p>
        img:<p><img src="{{url_for('students.download_file', name=student.img)}}"> </p>
        
        <br>
    {% endfor %}
<script>
    let x =3
    debugger
    console.log(x )
</script>



{% endblock %}

project/students/templates/upl.html
{% extends 'base.html' %}

{% block content %}

<h1>Upload new File</h1>
<form method=post enctype=multipart/form-data>
  <input type=file name=file>
  Name <input  name=stdent_name>
  age <input  type='number' name=age>
  <input type=submit value=Upload>
</form>

{% endblock %}